# Generated by Django 4.2.3 on 2023-08-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0002_country_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='country',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='currency',
        ),
    ]
