# Generated by Django 4.2.3 on 2023-08-21 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0003_remove_empresa_country_remove_empresa_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='country',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.country'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='currency',
            field=models.ForeignKey(blank=True, default=3, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.currency'),
        ),
        migrations.AddField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
