# Generated by Django 4.2.3 on 2023-08-21 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0004_empresa_country_empresa_currency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.country'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.currency'),
        ),
    ]
