# Generated by Django 4.2.3 on 2023-08-21 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0005_alter_empresa_country_alter_empresa_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.country'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.currency'),
        ),
    ]
