# Generated by Django 4.2.3 on 2023-08-23 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0006_alter_empresa_country_alter_empresa_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='currency',
        ),
    ]
