# Generated by Django 4.2.3 on 2023-11-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_coa', '0001_initial'),
        ('app_empresa', '0008_empresa_afecta_iva_empresa_plan_de_cuentas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='plan_de_cuentas',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_coa.coaname'),
        ),
    ]
