# Generated by Django 4.2.3 on 2023-11-23 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_coa', '0001_initial'),
        ('app_empresa', '0009_alter_empresa_plan_de_cuentas'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='def_cuentas_contables_activated',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='DefaultCuentasContablesEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('default_banco', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_banco', to='app_coa.coa')),
                ('default_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_compras', to='app_coa.coa')),
                ('default_honorarios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_honorarios', to='app_coa.coa')),
                ('default_iva_compras', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_iva_compras', to='app_coa.coa')),
                ('default_iva_ventas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_iva_ventas', to='app_coa.coa')),
                ('default_ventas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='default_ventas', to='app_coa.coa')),
            ],
        ),
        migrations.AddField(
            model_name='empresa',
            name='def_cuentas_contables',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.defaultcuentascontablesempresa'),
        ),
    ]
