# Generated by Django 4.2.3 on 2023-11-27 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0010_empresa_def_cuentas_contables_activated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='random_short_uuid',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
