# Generated by Django 4.2.3 on 2023-11-27 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0011_empresa_random_short_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='random_short_uuid',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
