# Generated by Django 4.2.3 on 2024-05-26 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.SmallIntegerField(unique=True)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('es_importacion', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MovInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_movimiento', models.DateTimeField(auto_now_add=True)),
                ('cantidad', models.PositiveIntegerField()),
                ('tipo_movimiento', models.CharField(choices=[('ENTRADA', 'ENTRADA'), ('SALIDA', 'SALIDA')], default='SALIDA', max_length=100)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('es_merma', models.BooleanField(default=False)),
                ('es_listo', models.BooleanField(default=False)),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_inventario.lote')),
                ('producto_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.productomaster')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.lote')),
                ('producto_master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_inventario.productomaster')),
            ],
        ),
    ]
