# Generated by Django 4.2.3 on 2023-08-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0001_initial'),
        ('app_banco', '0002_alter_banco_options_movimientobancario'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='negocio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.empresa'),
        ),
    ]
