# Generated by Django 4.2.3 on 2023-08-01 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0001_initial'),
        ('app_banco', '0003_movimientobancario_negocio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobancario',
            name='negocio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.empresa'),
        ),
    ]
