# Generated by Django 4.2.3 on 2023-08-01 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0003_comprobante_day_num_comprobante_month_num'),
        ('app_banco', '0005_movimientobancario_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobancario',
            name='comprobante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contabilidad.comprobante'),
        ),
    ]
