# Generated by Django 4.2.3 on 2023-08-01 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0006_alter_movimientobancario_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='day_num',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='month_num',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='year_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
