# Generated by Django 4.2.3 on 2023-08-02 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0009_alter_banco_empresa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimientobancario',
            name='negocio',
        ),
    ]
