# Generated by Django 4.2.3 on 2023-08-08 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0011_movimientobancario_monto_positivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimientobancario',
            name='day_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='month_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='movimientobancario',
            name='year_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
