# Generated by Django 4.2.3 on 2023-08-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0012_alter_movimientobancario_day_num_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='esta_contabilizado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='movimientobancario',
            name='monto_contabilizado',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
