# Generated by Django 4.2.3 on 2023-08-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0013_movimientobancario_esta_contabilizado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedioDePago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
