# Generated by Django 4.2.3 on 2023-08-21 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0002_country_currency'),
        ('app_banco', '0014_mediodepago'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediodepago',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.country'),
        ),
    ]
