# Generated by Django 4.2.3 on 2023-08-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0016_alter_mediodepago_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='medio_de_pago',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='app_banco.mediodepago'),
        ),
    ]
