# Generated by Django 4.2.3 on 2023-08-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0017_movimientobancario_medio_de_pago'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediodepago',
            name='mp_code2',
            field=models.CharField(blank=True, default='', max_length=2),
        ),
    ]
