# Generated by Django 4.2.3 on 2023-08-21 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0018_mediodepago_mp_code2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediodepago',
            name='mp_code2',
            field=models.CharField(default='', max_length=2),
        ),
    ]
