# Generated by Django 4.2.3 on 2023-08-23 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0019_alter_mediodepago_mp_code2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banco',
            name='country',
        ),
        migrations.RemoveField(
            model_name='banco',
            name='currency',
        ),
    ]
