# Generated by Django 4.2.3 on 2023-08-23 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0007_remove_empresa_currency'),
        ('app_banco', '0020_remove_banco_country_remove_banco_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='banco',
            name='currency',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.currency'),
        ),
    ]
