# Generated by Django 4.2.3 on 2023-08-23 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_banco', '0022_alter_banco_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientobancario',
            name='rut_chile',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
