# Generated by Django 4.2.3 on 2023-08-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='year_num',
            field=models.SmallIntegerField(default=0),
        ),
    ]
