# Generated by Django 4.2.3 on 2023-08-01 21:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_coa', '0001_initial'),
        ('app_contabilidad', '0003_comprobante_day_num_comprobante_month_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprobante',
            name='comprobante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad.comprobante'),
        ),
        migrations.AddField(
            model_name='registrocomprobante',
            name='cuenta_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_coa.coa'),
        ),
        migrations.AddField(
            model_name='registrocomprobante',
            name='debe',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='registrocomprobante',
            name='haber',
            field=models.IntegerField(default=0),
        ),
    ]
