# Generated by Django 4.2.3 on 2023-08-01 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0004_registrocomprobante_comprobante_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocomprobante',
            name='debe',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='registrocomprobante',
            name='haber',
            field=models.FloatField(default=0),
        ),
    ]
