# Generated by Django 4.2.3 on 2023-08-02 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0001_initial'),
        ('app_contabilidad', '0005_alter_registrocomprobante_debe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comprobante',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.empresa'),
        ),
        migrations.AddField(
            model_name='comprobante',
            name='id_unico',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
