# Generated by Django 4.2.3 on 2023-08-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0006_comprobante_empresa_comprobante_id_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='id_unico',
            field=models.CharField(max_length=50),
        ),
    ]
