# Generated by Django 4.2.3 on 2023-08-02 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0008_alter_comprobante_id_unico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='suma_debe',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='suma_haber',
            field=models.FloatField(default=0, editable=False),
        ),
    ]
