# Generated by Django 4.2.3 on 2023-08-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0009_alter_comprobante_suma_debe_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClienteProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=10)),
                ('name', models.CharField(blank=True, max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=20)),
                ('razon_social', models.CharField(max_length=120)),
                ('giro', models.CharField(blank=True, max_length=120)),
                ('tel_number', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_proveedor', models.BooleanField(default=False)),
                ('es_cliente', models.BooleanField(default=False)),
                ('es_extranjero', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumentoTributario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_documento', models.CharField(max_length=3)),
                ('nombre_documento', models.CharField(max_length=50)),
                ('country', models.CharField(choices=[('CHILE', 'Chile'), ('MEXICO', 'Mexico'), ('COLOMBIA', 'Colombia'), ('USA', 'Usa')], default='CHILE', max_length=20)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
    ]
