# Generated by Django 4.2.3 on 2023-08-03 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0001_initial'),
        ('app_contabilidad', '0010_clienteproveedor_tipodocumentotributario'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprobante',
            name='cliente_proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contabilidad.clienteproveedor'),
        ),
        migrations.CreateModel(
            name='CentroDeCostos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cc_slug', models.CharField(max_length=4)),
                ('cc_name', models.CharField(max_length=50)),
                ('cc_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.empresa')),
            ],
        ),
    ]
