# Generated by Django 4.2.3 on 2023-08-03 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0001_initial'),
        ('app_contabilidad', '0011_registrocomprobante_cliente_proveedor_centrodecostos'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprobante',
            name='centro_costo',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad.centrodecostos'),
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suc_slug', models.CharField(max_length=4)),
                ('suc_name', models.CharField(max_length=50)),
                ('cc_empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.empresa')),
            ],
        ),
    ]
