# Generated by Django 4.2.3 on 2023-08-03 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0012_registrocomprobante_centro_costo_sucursal'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprobante',
            name='sucurasl',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad.sucursal'),
        ),
    ]
