# Generated by Django 4.2.3 on 2023-08-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0013_registrocomprobante_sucurasl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocomprobante',
            name='centro_costo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad.centrodecostos'),
        ),
        migrations.AlterField(
            model_name='registrocomprobante',
            name='sucurasl',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad.sucursal'),
        ),
    ]
