# Generated by Django 4.2.3 on 2023-08-08 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0015_alter_registrocomprobante_centro_costo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='day_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='month_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='comprobante',
            name='year_num',
            field=models.SmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
