# Generated by Django 4.2.3 on 2023-08-08 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0016_alter_comprobante_day_num_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprobante',
            name='glosa',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
