# Generated by Django 4.2.3 on 2023-08-08 18:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0001_initial'),
        ('app_contabilidad', '0017_alter_comprobante_glosa'),
    ]

    operations = [
        migrations.CreateModel(
            name='LibroCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folio', models.IntegerField()),
                ('fecha_documento', models.DateField()),
                ('monto_exento', models.FloatField()),
                ('monto_neto', models.FloatField()),
                ('monto_iva', models.FloatField()),
                ('monto_total', models.FloatField()),
                ('es_cuadrado', models.BooleanField(default=False)),
                ('comprobante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contabilidad.comprobante')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_empresa.empresa')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_contabilidad.clienteproveedor')),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_contabilidad.tipodocumentotributario')),
            ],
        ),
    ]
