# Generated by Django 4.2.3 on 2023-08-08 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0018_librocompra'),
    ]

    operations = [
        migrations.AddField(
            model_name='librocompra',
            name='detalle',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
