# Generated by Django 4.2.3 on 2023-08-08 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0020_librocompra_ano_contable_librocompra_mes_contable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librocompra',
            name='ano_contable',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='librocompra',
            name='mes_contable',
            field=models.SmallIntegerField(),
        ),
    ]
