# Generated by Django 4.2.3 on 2023-08-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0023_alter_comprobante_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='librocompra',
            name='id_unico_dte',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
