# Generated by Django 4.2.3 on 2023-09-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contabilidad', '0031_librocompra_es_pagado'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrocomprobante',
            name='numero_documento',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
