# Generated by Django 4.2.3 on 2023-10-17 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_coa', '0001_initial'),
        ('app_contabilidad', '0033_libroventa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrocomprobante',
            name='cuenta_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_coa.coa'),
        ),
    ]
