# Generated by Django 4.2.3 on 2023-12-14 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_empresa', '0012_alter_empresa_random_short_uuid'),
        ('app_contabilidad', '0035_librocompra_es_anulado_libroventa_es_anulado'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteproveedor',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app_empresa.country'),
        ),
    ]
